### ISSUE TITLE
AttributeError: Can't get attribute 'DummyAgent' on <module 'joblib.externals.loky.backend.popen_loky_posix' from '/usr/local/lib/python3.8/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py'>

### ISSUE THREAD

**Issue by asmith26** [AirHockeyChallenge/air_hockey_challenge#27]
Hi there,

I'm trying to use the  [save/load functionality](https://air-hockey-challenges-docs.readthedocs.io/en/latest/agent.html#load-and-save-agent), but I seem to be getting an error - **not sure if I'm using this as intended?**

I first run `train.py` to save an agent: 

```python
import numpy as np
from air_hockey_challenge.framework import AirHockeyChallengeWrapper, AgentBase

class DummyAgent(AgentBase):
    def __init__(self, env_info, **kwargs):
        super().__init__(env_info, **kwargs)
        self.new_start = True
        self.hold_position = None

    def reset(self):
        self.new_start = True
        self.hold_position = None

    def draw_action(self, observation):
        if self.new_start:
            self.new_start = False
            self.hold_position = self.get_joint_pos(observation)

        velocity = np.zeros_like(self.hold_position)
        action = np.vstack([self.hold_position, velocity])
        return action


env = AirHockeyChallengeWrapper("7dof-hit")
agent = DummyAgent(env.env_info)
agent.save("./agent.msh", full_save=False)
```

then I update `agent_builder.py` to load this:

```python
from air_hockey_challenge.framework import AgentBase

def build_agent(env_info, **kwargs):
    agent = AgentBase.load_agent("/src/2023-challenge/agent.msh", env_info)
    return agent
```

Unfortunately I get the error (for some reason joblib can't seem to find `DummyAgent`):

```python
$ bash scripts/local_test.sh
[+] Building 0.6s (16/16) FINISHED                                                                                                                                                                                       docker:default
...
Start Local Testing
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/joblib/externals/loky/process_executor.py", line 428, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.8/dist-packages/joblib/externals/loky/process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/src/2023-challenge/air_hockey_challenge/framework/evaluate_agent.py", line 190, in _evaluate
    agent = agent_builder(mdp.env_info, **kwargs)
  File "/src/2023-challenge/air_hockey_agent/agent_builder.py", line 25, in build_agent
    agent = AgentBase.load_agent("/src/2023-challenge/agent.msh", env_info)
  File "/src/2023-challenge/air_hockey_challenge/framework/agent_base.py", line 77, in load_agent
    agent = cls.load(path)
  File "/usr/local/lib/python3.8/dist-packages/mushroom_rl/core/serialization.py", line 100, in load
    loaded_object = cls.load_zip(zip_file)
  File "/usr/local/lib/python3.8/dist-packages/mushroom_rl/core/serialization.py", line 110, in load_zip
    cls._load_pickle(zip_file, config_path).values()
  File "/usr/local/lib/python3.8/dist-packages/mushroom_rl/core/serialization.py", line 205, in _load_pickle
    return pickle.load(f)
AttributeError: Can't get attribute 'DummyAgent' on <module 'joblib.externals.loky.backend.popen_loky_posix' from '/usr/local/lib/python3.8/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "2023-challenge/run.py", line 124, in <module>
    evaluate(build_agent, **config)
  File "/src/2023-challenge/air_hockey_challenge/framework/evaluate_agent.py", line 72, in evaluate
    data = Parallel(n_jobs=n_cores)(delayed(_evaluate)(path, env, agent_builder, chunks[i], quiet, render,
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
AttributeError: Can't get attribute 'DummyAgent' on <module 'joblib.externals.loky.backend.popen_loky_posix' from '/usr/local/lib/python3.8/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py'>
```

Thanks!

**Comment by cube1324** [comment]
Hello,
the problem is that the load function in `agent_builder.py` cannot find the DummyAgent class in its path. For the load function to find this class it needs to have the exact same import path in both the file where the agent is saved and where its loaded. This can be annoying for small examples as the above because saving the agent in the same class as it is declared leads to different import paths between the load and save file. So a working example would be:

A file with the Dummy Agent class `air_hockey_agent/agent_builder.py`:
```python
import numpy as np
from air_hockey_challenge.framework import AgentBase

class DummyAgent(AgentBase):
    def __init__(self, env_info, **kwargs):
        super().__init__(env_info, **kwargs)
        self.new_start = True
        self.hold_position = None

    def reset(self):
        self.new_start = True
        self.hold_position = None

    def draw_action(self, observation):
        if self.new_start:
            self.new_start = False
            self.hold_position = self.get_joint_pos(observation)

        velocity = np.zeros_like(self.hold_position)
        action = np.vstack([self.hold_position, velocity])
        return action
```

and a file which will save this agent `air_hockey_agent/train.py`:

```python
from air_hockey_challenge.framework import AirHockeyChallengeWrapper
# important import, has to be same in agent_builder
from air_hockey_agent.dummy_agent import DummyAgent

env = AirHockeyChallengeWrapper("7dof-hit")
agent = DummyAgent(env.env_info)
agent.save("./agent.msh", full_save=False)
```

Then you can load the agent in `air_hockey_agent/agent_builder.py`:
```python
from air_hockey_challenge.framework import AgentBase
from pathlib import Path
# Important import
from air_hockey_agent.dummy_agent import DummyAgent

def build_agent(env_info, **kwargs):
    base_dir = Path(__file__).parent
    # Assume the file is in air_hockey_agent/agent.msh
    agent = AgentBase.load_agent(base_dir.joinpath("agent.msh"), env_info)
    return agent
```

Also in order to actually save attributes of the class you have to add them with the `self._add_save_attr()` call.

**Comment by asmith26** [comment]
Many thanks for the detailed response, I've got this working now :)
