### ISSUE TITLE
rendering simulator error 

### ISSUE THREAD

**Issue by dd913** [AirHockeyChallenge/air_hockey_challenge#3]
after setting up the docker I run the example 
```
python run.py --n_cores 1 -e 3dof-hit --example hit-agent --n_episodes 5
```
there are no problems, but when I run the following code to see the simulator I get the following error:

```
python run.py -r -e 3dof-hit --example hit-agent --n_cores 1 --n_episodes 5
```
```
  0%|                                                     | 0/5 [00:00<?, ?it/s]libGL error: MESA-LOADER: failed to retrieve device information
Traceback (most recent call last):
  File "run.py", line 125, in <module>
    evaluate(build_agent, **config)
  File "/src/2023-challenge/air_hockey_challenge/framework/evaluate_agent.py", line 71, in evaluate
    data = Parallel(n_jobs=n_cores)(delayed(_evaluate)(path, env, agent_builder, chunks[i], quiet, render,
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 597, in __init__
    self.results = batch()
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/src/2023-challenge/air_hockey_challenge/framework/evaluate_agent.py", line 206, in _evaluate
    dataset, success, penalty_sum, constraints_dict, jerk, computation_time, violations = compute_metrics(core, eval_params, episode_offset)
  File "/src/2023-challenge/air_hockey_challenge/framework/evaluate_agent.py", line 219, in compute_metrics
    dataset, dataset_info = core.evaluate(**eval_params, get_env_info=True)
  File "/usr/local/lib/python3.8/dist-packages/mushroom_rl/core/core.py", line 99, in evaluate
    return self._run(n_steps, n_episodes, fit_condition, render, quiet, get_env_info,
  File "/usr/local/lib/python3.8/dist-packages/mushroom_rl/core/core.py", line 128, in _run
    dataset, dataset_info = self._run_impl(move_condition, fit_condition, steps_progress_bar,
  File "/usr/local/lib/python3.8/dist-packages/mushroom_rl/core/core.py", line 151, in _run_impl
    sample, step_info = self._step(render)
  File "/src/2023-challenge/air_hockey_challenge/framework/challenge_core.py", line 36, in _step
    self.mdp.render()
  File "/src/2023-challenge/air_hockey_challenge/framework/air_hockey_challenge_wrapper.py", line 82, in render
    self.base_env.render()
  File "/usr/local/lib/python3.8/dist-packages/mushroom_rl/environments/mujoco.py", line 171, in render
    self._viewer = MujocoGlfwViewer(self._model, self.dt, **self._viewer_params)
  File "/usr/local/lib/python3.8/dist-packages/mushroom_rl/utils/mujoco/viewer.py", line 52, in __init__
    self._context = mujoco.MjrContext(model, mujoco.mjtFontScale(100))
mujoco.FatalError: OpenGL version 1.5 or higher required
```

**Comment by PuzeLiu** [comment]
Can you provide more details about your setup info, such as GPU, Linux or Windows?  We will try to look into it. 

In addition, you can use your local environment, such as conda, to develop your agent. The modification in your air_hockey_challenge folder is automatically synchoronized. Then, put python dependencies in the requirements.txt.
The cloud evaluation will disable the rendering as well.

**Comment by dd913** [comment]
> Can you provide more details about your setup info, such as GPU, Linux or Windows? We will try to look into it.
> 
> In addition, you can use your local environment, such as conda, to develop your agent. The modification in your air_hockey_challenge folder is automatically synchoronized. Then, put python dependencies in the requirements.txt. The cloud evaluation will disable the rendering as well.

```AMD® Iceland / Mesa Intel® UHD Graphics 620 (KBL GT2)```, ```Ubuntu 20.04.5 LTS (Focal Fossa)``` and I am using conda, I am having this issue after running ```docker compose run challenge``` then when I run the ```python run.py -r -e 3dof-hit --example hit-agent --n_cores 1 --n_episodes 5``` you know the following

**Comment by PuzeLiu** [comment]
Is the rendering work if you don't start docker? You can try to run the command in the conda env directly without starting docker. 
`python run.py -r -e 3dof-hit --example hit-agent --n_cores 1 --n_episodes 5`

If it's fine, I think maybe check also the `OpenGL` version in your docker image. After you start the docker `docker compose run challenge`, can you check

```
apt update
apt install mesa-utils
glxinfo | grep "OpenGL version"
```

**Comment by dd913** [comment]
> Is the rendering work if you don't start docker? You can try to run the command in the conda env directly without starting docker. `python run.py -r -e 3dof-hit --example hit-agent --n_cores 1 --n_episodes 5`
> 
> If it's fine, I think maybe check also the `OpenGL` version in your docker image. After you start the docker `docker compose run challenge`, can you check
> 
> ```
> apt update
> apt install mesa-utils
> glxinfo | grep "OpenGL version"
> ```

yes it works before ```docker compose run challenge```
I did the things you have said,problem still exist, the answer is ```string: 1.3 Mesa 21.2.6```
That means I have to update it myself manually,okay thanks

**Comment by PuzeLiu** [comment]
Great! If you want to make the installation works permanently, you could append the installation commad at the bottom of the `Dockerfile`.
