### ISSUE TITLE
Specify the version of numpy in the requirements.txt file.

### ISSUE THREAD

**Issue by TexnoMann** [AirHockeyChallenge/air_hockey_challenge#9]
I have problem when I tried run Warm-Up environment using directly python env.
```python
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe  
Traceback (most recent call last):  
  File "/media/files/projects/DIPLOMA/air_hockey_challenge/run.py", line 113, in <module>  
    from examples.control.hitting_agent import build_agent  
  File "/media/files/projects/DIPLOMA/air_hockey_challenge/examples/control/hitting_agent.py", line 7, in <module>  
    from baseline.baseline_agent import BezierPlanner, TrajectoryOptimizer  
  File "/media/files/projects/DIPLOMA/air_hockey_challenge/baseline/baseline_agent/__init__.py", line 2, in <module>  
    from .optimizer import TrajectoryOptimizer  
  File "/media/files/projects/DIPLOMA/air_hockey_challenge/baseline/baseline_agent/optimizer.py", line 5, in <module>  
    import nlopt
  File "/home/texnoman/.local/lib/python3.10/site-packages/nlopt/__init__.py", line 1, in <module>
    from .nlopt import *
  File "/home/texnoman/.local/lib/python3.10/site-packages/nlopt/nlopt.py", line 20, in <module>
    from . import _nlopt
ImportError: numpy.core.multiarray failed to import
```
Updating manually `numpy 1.24` fixed the issue. I think this can be resolved by adding `numpy==1.24.2` to the requirements.

**Comment by PuzeLiu** [comment]
Hi, thanks for sharing. We will add the numpy requirement in the futher update.
